/**
 * LawConnect — Legal Situation Wizard Route
 * File: routes/wizard.js
 *
 * POST /api/wizard
 * Body:    { prompt: string, area?: string }
 * Returns: { reply: string, confidence: string, reason: string }
 *
 * Accepts the focused prompt generated by the frontend Legal Situation Wizard
 * and returns a direct, actionable LexAI answer using the QUICK_QUESTION_PROMPT.
 * This prompt is tuned for brevity and actionability — perfect for wizard outputs.
 */

const express = require('express');
const { chatLimiter }          = require('../middleware/rateLimiter');
const { validateWizardBody }   = require('../middleware/validate');
const { complete }             = require('../utils/groq');
const { QUICK_QUESTION_PROMPT } = require('../config/prompts');

const router = express.Router();

/* ── POST /api/wizard ── */
router.post('/', chatLimiter, validateWizardBody, async (req, res) => {
  try {
    const { prompt, area } = req.body;

    // Enhance prompt with the area context if provided
    const fullPrompt = area
      ? `[Legal Area: ${area}]\n\n${prompt}`
      : prompt;

    const { reply, confidence, reason } = await complete({
      systemPrompt: QUICK_QUESTION_PROMPT,
      messages:     [{ role: 'user', content: fullPrompt }],
      maxTokens:    600,   // wizard answers should be concise
    });

    return res.json({ reply, confidence, reason });

  } catch (err) {
    console.error('[/api/wizard] Error:', err.message);

    if (err?.status === 429) {
      return res.status(429).json({ error: 'AI service is busy. Please wait a moment.' });
    }
    return res.status(500).json({ error: 'Failed to process your question. Please try again.' });
  }
});

module.exports = router;
